import { ImageResponse } from 'next/og'
import { OG_THEME, OG_TAGLINES, type OgLocale } from '@/lib/og-theme'

export const runtime = 'edge'

/**
 * GET /api/og?locale=nl
 *
 * Dynamic per-locale OG image, rendered via next/og (Satori).
 * Falls back to NL tagline on unknown locale. Cached aggressively because
 * the output only changes when OG_TAGLINES or OG_THEME change.
 *
 * NOTE: static /og-image.png (1200x630, generated by scripts/generate-brand-assets.mjs)
 * stays the default OG image referenced by metadata. This dynamic route is
 * available but not wired into per-locale metadata yet — a follow-up plan
 * will switch the metadata to call this route per locale once Daley
 * confirms the rendered output matches the static asset visually.
 */
export async function GET(request: Request): Promise<Response> {
  const { searchParams } = new URL(request.url)
  const localeParam = searchParams.get('locale') ?? 'nl'
  const locale: OgLocale = localeParam in OG_TAGLINES ? (localeParam as OgLocale) : 'nl'
  const tagline = OG_TAGLINES[locale]

  return new ImageResponse(
    (
      <div
        style={{
          width: '1200px',
          height: '630px',
          background: OG_THEME.bgDeep,
          color: OG_THEME.textPrimary,
          display: 'flex',
          flexDirection: 'column',
          padding: '64px',
          fontFamily: 'sans-serif',
        }}
      >
        <div style={{ display: 'flex', fontSize: 32, color: OG_THEME.accentSystem }}>
          future-marketing.ai
        </div>
        <div
          style={{
            flex: 1,
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <div
            style={{
              display: 'flex',
              fontSize: 180,
              fontWeight: 700,
              color: OG_THEME.accentSystem,
            }}
          >
            Clyde
          </div>
          <div
            style={{
              display: 'flex',
              fontSize: 48,
              color: OG_THEME.textPrimary,
              marginTop: 16,
              maxWidth: 1000,
              textAlign: 'center',
            }}
          >
            {tagline}
          </div>
        </div>
        <div
          style={{
            display: 'flex',
            justifyContent: 'flex-end',
            fontSize: 24,
            color: OG_THEME.textSecondary,
          }}
        >
          {locale.toUpperCase()}
        </div>
      </div>
    ),
    {
      width: 1200,
      height: 630,
      headers: {
        'cache-control': 's-maxage=31536000, stale-while-revalidate',
      },
    }
  )
}
