import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

export const alt = 'Future Marketing AI: AI-Powered Marketing Automation'
export const size = { width: 1200, height: 630 }
export const contentType = 'image/png'

/*
 * Per-locale OG endpoint that serves the static branded Synapse card
 * generated by scripts/generate-brand-assets.mjs.
 *
 * Why not Satori (next/og)? In Next.js 16 the dynamic ImageResponse stream
 * crashes mid-flight ("failed to pipe response") on this project — HEAD
 * returns 200 but the GET body never completes. Reproducible across all
 * locales and template variants (with and without inline SVG). Tracking
 * upstream; in the meantime the static asset carries identical visual
 * identity per locale (title/description live in <meta> tags, not the OG
 * image — Google/LinkedIn/Twitter pull both separately).
 *
 * The static og-image.png is brand-correct (Synapse mark, Clyde headline,
 * Dutch agency tagline) and regenerable via the brand-assets script.
 */
export default async function Image() {
  const png = await readFile(join(process.cwd(), 'public/og-image.png'))
  return new Response(new Uint8Array(png), {
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': 'public, max-age=31536000, immutable',
    },
  })
}
